= Quickstart projects for meta-updater

== Getting started

This repo is not to be cloned directly, use https://source.android.com/source/downloading.html[Android repo]
tool instead:

    sudo apt-get install repo
    repo init -u https://github.com/advancedtelematic/updater-repo.git
    repo sync -j8

Install the OpenEmbedded build dependencies:

    sudo apt-get install gawk wget git-core diffstat unzip texinfo gcc-multilib \
     build-essential chrpath socat libsdl1.2-dev xterm repo

A convenience script is provided to set up your environment to produce OTA-enabled image
for your machine:

    source meta-updater/scripts/envsetup.sh <machine> # One of intel-corei7-64 (for Minnowboard), raspberrypi3, or qemux86-64


Then you can build the required image (core-image-minimal is a good start)

    bitbake core-image-minimal


For instructions how to link the device to ATS Garage, see http://docs.atsgarage.com/start-yocto/your-first-ostreeenabled-yocto-project.html


== Running the image (Minnowboard Max/Turbot)

Write the image with the following command (replace /dex/sdX with the correct device for your microSD card):

    sudo dd if=tmp/deploy/images/intel-corei7-64/core-image-minimal-intel-corei7-64.wic of=/dev/sdX bs=32M && sync

The image file Yocto generates is shrunk down to the smallest it can be. After writing it to your SD card, you’ll want to expand the partition and root filesystem so they use the whole disk:

    sudo parted  /dev/sdX
    (parted) resizepart
    Warning: Not all of the space available to /dev/sdh appears to be used, you can fix the GPT to use all of the space (an extra 15346552 blocks) or continue with the current setting?
    Fix/Ignore? fix
    Partition number? 2
    End?  [112MB]? 100%
    (parted) quit
    sudo resize2fs /dev/sdX2

Now insert the microSD card in the Minnowboard Max and boot it.

== Running the image (Raspberry Pi 3)

Build the `rpi-basic-image`:

    bitbake rpi-basic-image

Write it to a SD card:

    sudo dd if=tmp/deploy/images/raspberrypi3/rpi-basic-image-raspberrypi3.rpi-sdimg-ota of=/dev/sdh bs=32M && sync
    sudo parted -s /dev/sdX resizepart 2 '100%'
    sudo resize2fs /dev/sdX2


== Running the image (Qemu)

    ../meta-updater/scripts/run-qemu-ota <imagename>

This script will run 'core-image-minimal' by default if no image name is given. Use `run-qemu-ota -h` for a list of command line options.

In particular, you may create/use a qcow2-formatted storage overlay file for persistence. If you don't, any changes you make to the image will be lost as soon as qemu terminates. You can do this with `-o mylayer.cow`; that will create the file if it doesn't exist, and use it if it does.
