= Quickstart projects for meta-updater

== Getting started

This repo is not intended to be cloned directly. Use the https://source.android.com/source/downloading.html[Android repo] tool instead:

    sudo apt install repo
    repo init -u https://github.com/advancedtelematic/updater-repo.git -m thud.xml
    repo sync -j8

You should specify a particular branch when initializing. Currently Thud (2.6) and Warrior (2.7) are supported; older ones are available but not actively maintained. For more information about supported branches, please refer to the https://docs.ota.here.com/ota-client/latest/yocto-release-branches.html[documentation portal]

Install the build dependencies for https://www.yoctoproject.org/docs/2.6/ref-manual/ref-manual.html#required-packages-for-the-build-host[OpenEmbedded] and https://github.com/advancedtelematic/meta-updater/[meta-updater]. See https://docs.ota.here.com/ota-client/dev/build-raspberry.html[the documentation portal] for more information.

A convenience script is provided to set up your environment to produce OTA-enabled images for your target device:

    source meta-updater/scripts/envsetup.sh <machine>  # for example, raspberrypi3 or qemux86-64

A list of supported boards can be found on the https://docs.ota.here.com/ota-client/latest/supported-boards.html[documentation portal].

Then you can build an image. `core-image-minimal` is a good start:

    bitbake core-image-minimal

For more documentation on using these repos and https://connect.ota.here.com/[HERE OTA Connect], please see the https://docs.ota.here.com/[OTA Connect documentation portal].
